servers:
  mcp_bridge:
    host: 127.0.0.1
    port: 8001
  unity_editor:
    host: 127.0.0.1
    port: 8001
  blender_addon:
    host: 127.0.0.1
    port: 8002
paths:
  unity_project: unity_project
  blender_export: unity_project/Assets/Generated
  templates: templates
logging:
  level: INFO
  file: logs/app.log
timeouts:
  mcp_bridge: 15
  unity_editor: 15
  blender_addon: 20
agent:
  mcp:
    adapterOwnership: agent_runner_only
gateway:
  processes:
    unity:
      exe: C:/Program Files/Unity/Hub/Editor/6000.2.5f1/Editor/Unity.exe
      args: []
      project_path: ''
      timeout: 20
    unity_bridge:
      host: 127.0.0.1
      port: 8001
      timeout: 15
    blender:
      exe: C:/Program Files/Blender Foundation/Blender 4.5/blender.exe
      args: []
      timeout: 20
    mcp_adapter:
      python: C:/projects/ai-gamedev-pipeline/venvs/adapter/Scripts/python.exe
      script_path: bridges/mcp_adapter.py
      timeout: 10
    blender_bridge:
      port: 8002
  config:
    providers:
      geminiCli:
        showConsole: true
        command: C:/Users/PC/AppData/Roaming/npm/gemini.cmd
      gemini_cli:
        node_executable_path: node.exe
        gemini_script_path: C:/Users/PC/AppData/Roaming/npm/node_modules/@google/gemini-cli/dist/index.js
    project_dir_base: C:/projects/ai-gamedev-pipeline/gateway/projects
    version: '1.0'
    executables:
      unityExecutablePath: C:/Program Files/Unity/Hub/Editor/6000.2.5f1/Editor/Unity.exe
      blenderExecutablePath: C:/Program Files/Blender Foundation/Blender 4.5/blender.exe
      unityProjectRoot: unity_project
    bridges:
      unityBridgePort: 8001
      blenderBridgePort: 8002
    integrations:
      gemini:
        apiKey: null
        defaultModel: ''
      openai:
        apiKey: null
        defaultModel: gpt-4o
      anthropic:
        apiKey: null
        defaultModel: claude-3-sonnet-20240229
    projects:
      root: unity_project
