servers:
  mcp_bridge:
    host: 127.0.0.1
    port: 8001
  unity_editor:
    host: 127.0.0.1
    port: 8001
  blender_addon:
    host: 127.0.0.1
    port: 8002
paths:
  unity_project: unity_project
  blender_export: unity_project/Assets/Generated
  templates: templates
logging:
  level: INFO
  file: logs/app.log
timeouts:
  mcp_bridge: 15
  unity_editor: 15
  blender_addon: 20
