# AI Gateway Configuration
gateway:
  server:
    host: "127.0.0.1"
    port: 8000
    reload: true
  cors:
    allow_origins:
      - "http://localhost:5173"
      - "http://127.0.0.1:5173"
    allow_credentials: true
    allow_methods: ["*"]
    allow_headers: ["*"]
  chat:
    max_message_length: 4000
    history_limit_default: 50

servers:
  mcp_bridge:
    host: 127.0.0.1
    port: 8001
  unity_editor:
    host: 127.0.0.1
    port: 8001
  blender_addon:
    host: 127.0.0.1
    port: 8002

paths:
  unity_project: unity_project
  blender_export: unity_project/Assets/Generated
  templates: templates

logging:
  level: INFO
  file: logs/app.log

timeouts:
  mcp_bridge: 15
  unity_editor: 15
  blender_addon: 20

