servers:
  mcp_bridge:
    host: 127.0.0.1
    port: 8001
  unity_editor:
    host: 127.0.0.1
    port: 8001
  blender_addon:
    host: 127.0.0.1
    port: 8002
paths:
  unity_project: unity_project
  blender_export: unity_project/Assets/Generated
  templates: templates
logging:
  level: INFO
  file: logs/app.log
timeouts:
  mcp_bridge: 15
  unity_editor: 15
  blender_addon: 20
agent:
  mcp:
    adapterOwnership: agent_runner_only
gateway:
  processes:
    unity:
      exe: C:/Program Files/Unity/Hub/Editor/6000.0.15f1/Editor/Unity.exe
      args: []
      project_path: ''
      timeout: 20
    unity_bridge:
      host: 127.0.0.1
      port: 8001
      timeout: 15
    blender:
      exe: D:/blender/blender.exe
      args: []
      timeout: 20
    mcp_adapter:
      python: D:/ai-gamedev-pipeline/venvs/adapter/Scripts/python.exe
      script_path: bridges/mcp_adapter.py
      timeout: 10
  config:
    providers:
      geminiCli:
        command: C:\Users\oarjo\AppData\Roaming\npm\gemini.CMD
        showConsole: true
